import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

import { SoundProvider } from '@/context/SoundContext'

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SoundProvider>
          {children}
        </SoundProvider>
      </body>
    </html>
  )
}
